### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by zzownszz** [kevin-256/InstagramAccountsExtrator#1]
Olá, poderia explicar com detalhes para um leigo de como utilizar?

**Comment by kevin-256** [comment]
WARNING: never copy and paste code from unknown sources to the browser javascript console without knowing what it does. This code is not yet complete and may still have some bugs.

You need python to use this program and a browser with instagram website opened and logged in with an account.
If you want to compare the followers/following of two account that you follow or that are public:

1. Launch the script with the two username as arguments, like  `python3 commonUsers.py username1 username2`.
2. Paste the code, that the script automatically has copied in the clipboard, in the javascript console of the tab of the browser that has instagram loaded.
3. Wait for the process to end, and return to the Python console without closing the browser.
4. Choose whether you want the followers or followings list from the first user by entering 0 or 1 in the Python console and pressing Enter.
5. Paste another time the code from the clipboard in the javascript console of the browser.
6. Open the file in the script's folder with the name  `username1_year_month_day.json` and paste the content of the clipboard.
7. Press Enter in the python console to confirm that you have written the json in the file.
8. Do the same thing (step 2 to step 7)for the second user.
9. The script will now display users found in both the followers or following list, based on your choice in step 4, along with the final size of that list.

If you need only the following/follower list of one user that you follow or that is public:
1. Launch the script with the username as an argument, like  `python3 commonUsers.py username1`.
2. Paste the code, that the script automatically has copied in the clipboard, in the javascript console of the tab of the browser that has instagram loaded.
3. Wait for the process to end, and return to the Python console without closing the browser.
4. Choose whether you want the followers or followings list from the first user by entering 0 or 1 in the Python console and pressing Enter.
5. Paste another time the code from the clipboard in the javascript console of the browser.
6. Open the file in the script's folder with the name  `username1_year_month_day.json` and paste the content of the clipboard.
7. Press Enter in the python console to confirm that you have written the json in the file.
8. The script will now display users found in the followers or following list, based on your choice in step 4, along with the final size of that list.

If you need only to retrive the username list from an old json file:
1. Launch the script with the filename as an argument, like  `python3 commonUsers.py username1_2023_03_10.json`.
2. The script will now display users found in the followers or following list, along with the final size of that list.

**Comment by zzownszz** [comment]
Hello, thank you for getting back to me, it generated this error when pasting into the console, so I went through the entire process, but in the end the generated json file is generated empty (with nothing inside) probably because of this error, I am logged into a profile. instagram and I'm trying to run the code in the console and return this error.

Process started! Give it a couple of seconds
Promise {<pending>}
VM249:110 {err: TypeError: Cannot read properties of undefined (reading 'user')
    at <anonymous>:22:43}

**Comment by kevin-256** [comment]
if you copy the code from the js file into the javascript console you made a mistake. You have to run the code and it generate and automatically copy it in your clipboard, so you have only to paste it in the console. Or you mispelled the username of an account

**Comment by zzownszz** [comment]
Perfect, amazing, thanks for the feedback, it worked beautifully, I just had one question, it generated my entire list correctly in the terminal, to save the list of names from the terminal I select it manually or is there another way to automatically save the usernames one below from the other the same generates in the terminal?

example:
username1
username2
username3
User list count: 3679

Another question, is there a way to create a script that does this automatically, through a function/call it pulls followers from a page determined by the user and it does an automation for example with Selenium that opens a Chrome browser, pastes these codes into the console by example or something like that? and in the end it generates a file with the users one below the other in txt for example? you managed to understand the idea, anything I can detail better, thank you.

**Comment by kevin-256** [comment]
Yes you have to copy it manually for now, in the next version it will save it in a file and show it in a gui to spot the different users easier. And yes I could use selenium, it will be a nice upgrade for the next version. If you have other questions or suggestions for improving the program, don't hesitate to contact me.

**Comment by zzownszz** [comment]
Yes, this Selenium example is a good idea, thank you for your feedback and attention, I'm sure that when the update comes out, it will be even better, if you need anything I'm also happy to help.

Let me ask you, have you developed anything else focused on or related to Instagram? I'm already loving your codes xD

**Comment by kevin-256** [comment]
I was recreating the same software in Java to have a nice gui instead of just the cli, but for now it's still about halfway done. You can find the "useful" software I wrote in my github, for now there's only this one related to Instagram.

**Comment by zzownszz** [comment]
Perfect, one question, is it possible to extract more information besides the username and full name, such as telephone number, email if they are public?

**Comment by kevin-256** [comment]
Not at the moment

**Comment by zzownszz** [comment]
Good morning honey how are you?

Another question, do you know what the maximum number of followers it can download is, for example up to 100k followers?

**Comment by kevin-256** [comment]
Hi, the limit is the size of your computer's clipboard, therefore very large

**Comment by zzownszz** [comment]
Perfect, thanks for the answer, let me ask you something else, do you have anything that you can share, whether authorial or from someone else that you have seen, that I can use in Python to pull information from a profile, example followers, following, number of publications and account insights?

**Comment by kevin-256** [comment]
you can find something in the youtube channel "Aaron Jack"

**Comment by zzownszz** [comment]
peerfect, I'll look, thanks :)
